language: python
python:
  - "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: pip install -r requirements.txt --use-mirrors && pip install -r test_requirements.txt
script: make test && make jasmine
